<dialog id="new-budget" class="modal" aria-labelledby="new-budget-title">
<div class="modal-box max-w-xl"><h2 class="text-xl font-bold" id="new-budget-title">Start a budget</h2><p class="mt-2 text-sm opacity-70">Start from a calendar month, your pay cycle, or any custom period.</p>
<form method="post" action="{{ route('budgets.store') }}" data-budget-action class="mt-5 space-y-4">@csrf
<label class="block"><span class="label">Budget name</span><input class="input w-full" name="name" value="My budget" maxlength="100" required></label>
<label class="block"><span class="label">Who is this for?</span><select name="scope" class="select w-full" data-budget-scope><option value="personal">Personal - only me</option><option value="household">Household - invite viewers or editors</option></select></label>
<div class="grid gap-4 sm:grid-cols-2"><label><span class="label">Start date (included)</span><input class="input w-full" type="date" name="start_date" value="{{ now()->startOfMonth()->toDateString() }}" required></label><label><span class="label">End date (included)</span><input class="input w-full" type="date" name="end_date" value="{{ now()->endOfMonth()->toDateString() }}" required></label></div>
<label class="block"><span class="label">Expected income (ZAR)</span><input class="input w-full" type="number" name="expected_income" min="0" step="0.01" value="0" required></label>
<label class="block"><span class="label">Copy an existing plan (optional)</span><select name="copy_from" class="select w-full"><option value="">Start fresh</option>@foreach($budgets as $existingBudget)@can('update', $existingBudget)@foreach($existingBudget->periods as $existingPeriod)<option value="{{ $existingPeriod->id }}">{{ $existingBudget->name }}: {{ $existingPeriod->start_date->format('d M Y') }} - {{ $existingPeriod->end_date->format('d M Y') }}</option>@endforeach
@endcan
@endforeach</select><span class="mt-1 block text-xs opacity-60">Copying uses the source allocations and expected income instead of the inputs above. Received income and transactions are never copied.</span></label>
<label class="block"><span class="label">Repeat this pay cycle</span><select name="repeat_cycle" class="select w-full"><option value="none">Off - choose each period</option><option value="monthly">Monthly, using this start day</option><option value="fixed_days">Same number of days</option></select><span class="mt-1 block text-xs opacity-60">This pre-fills the next period when you copy your plan. No automatic carry-over.</span></label>
<input type="hidden" name="starter_categories" value="0"><label class="flex items-start gap-3"><input type="checkbox" class="checkbox checkbox-sm" name="starter_categories" value="1" checked><span class="text-sm">Use starter categories</span></label>
<input type="hidden" name="include_subscriptions" value="0"><label class="flex items-start gap-3"><input type="checkbox" class="checkbox checkbox-sm" name="include_subscriptions" value="1" checked data-budget-include><span class="text-sm">Include my subscriptions. In a household budget, their names, prices, and payment dates become visible to invited members.</span></label>
<div class="modal-action"><button class="btn btn-ghost" type="button" data-close-dialog>Cancel</button><button class="btn btn-primary" type="submit">Create budget</button></div>
</form></div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>