<div class="space-y-8">
@include('budgets.groups')
<div class="flex flex-wrap items-center justify-between gap-3"><p class="text-sm opacity-60">Set your income and category limits. Changes save automatically.</p>@if($canEdit)<button class="btn btn-sm btn-outline" data-open-dialog="budget-income" type="button">Add income</button>@endif</div>
        <section class="space-y-4" aria-labelledby="budget-categories-title"><div class="flex flex-wrap items-center justify-between gap-3"><h3 class="text-xl font-semibold" id="budget-categories-title">Your category plan</h3>@if($canEdit)<div class="flex gap-2"><button class="btn btn-sm btn-outline" type="button" data-open-dialog="budget-category">Add category</button><button class="btn btn-sm btn-ghost" type="button" data-open-dialog="budget-transfer">Move money</button></div>@endif</div>
        <div class="space-y-6">
        @foreach($categoryRows->groupBy(fn (array $row): int => $row['category']->budget_group_id ?? 0) as $groupId => $rows)
            @if($groups->isNotEmpty())<div class="flex items-center gap-3"><h4 class="font-semibold">{{ $groups->firstWhere('id', $groupId)?->name ?? 'Ungrouped' }}</h4><span class="badge badge-sm badge-ghost">{{ $rows->count() }} categories</span></div>@endif
            <div class="space-y-3">
            @foreach($rows as $row)@php $category = $row['category']; @endphp
            <article class="rounded-sm border border-base-300 bg-base-100 p-4">
                @if($canEdit)<form method="post" action="{{ $actionUrl('category-save') }}" data-budget-action data-budget-autosave class="flex flex-wrap items-end gap-3">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value="{{ $category->id }}"><label class="min-w-0 flex-1"><span class="label">Category</span><input class="input input-sm w-full" name="name" value="{{ $category->name }}" maxlength="100" required @readonly($category->kind !== 'custom')></label><label><span class="label">Limit ({{ $currencySymbol }})</span><input class="input input-sm w-36" type="number" name="amount" step="0.01" min="0" value="{{ $amount($row['planned']) }}" required data-category-limit></label>@if($category->kind === 'subscriptions')<input type="hidden" name="automatic" value="0"><label class="flex items-center gap-2 text-xs"><input class="checkbox checkbox-sm" type="checkbox" name="automatic" value="1" @checked($category->allocated_cents === null)>Follow subscription forecast</label>@endif<noscript><button type="submit" class="btn btn-sm">Save</button></noscript></form>@else<h4 class="font-semibold">{{ $category->name }}</h4>@endif
                @if($canEdit && $groups->isNotEmpty())
                <form method="post" action="{{ $actionUrl('category-group') }}" data-budget-action class="mt-3 flex flex-wrap items-center gap-2" data-budget-group-assignment>@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value="{{ $category->id }}"><label class="flex items-center gap-2 text-xs"><span>Group</span><select class="select select-sm" name="group_id"><option value="">Ungrouped</option>@foreach($groups as $group)<option value="{{ $group->id }}" @selected($category->budget_group_id === $group->id)>{{ $group->name }}</option>@endforeach</select></label><noscript><button class="btn btn-sm" type="submit">Assign</button></noscript></form>
                @endif
                <div class="mt-3 space-y-2" data-budget-live="category-{{ $category->id }}"><div class="flex flex-wrap justify-between gap-2 text-sm"><span>Spent {{ $money($row['spent']) }} of {{ $money($row['planned']) }}</span><span @class(['font-semibold', 'text-error' => $row['remaining'] < 0])>{{ $row['remaining'] < 0 ? 'Over by ' : 'Remaining ' }}{{ $money(abs($row['remaining'])) }}</span></div><progress @class(['progress w-full', 'progress-error' => $row['spent'] > $row['planned'], 'progress-primary' => $row['spent'] <= $row['planned']]) value="{{ min($row['spent'], max(1, $row['planned'])) }}" max="{{ max(1, $row['planned']) }}" aria-label="Spending against the {{ $category->name }} limit"></progress>@if($row['upcoming'] > 0)<p @class(['text-xs', 'text-error' => $row['available'] < 0, 'opacity-60' => $row['available'] >= 0])>Unpaid charges: {{ $money($row['upcoming']) }} · Available after these: {{ $money($row['available']) }}</p>@endif</div>
                @if($canEdit && $category->kind === 'custom')<form method="post" action="{{ $actionUrl('category-remove') }}" data-budget-action data-confirm="Remove this category? Its expenses move to Other and its allocation is freed." class="mt-2">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value="{{ $category->id }}"><button class="btn btn-xs btn-ghost" type="submit">Remove category</button></form>@endif
            </article>
            @endforeach
            </div>
        @endforeach</div></section>
    <section id="budget-incomes" class="space-y-4"><h3 class="text-xl font-semibold">Income sources</h3><p class="text-sm opacity-70">Expected income funds your plan. Record received income separately.</p>@forelse($incomes as $income)<div class="rounded-sm border border-base-300 bg-base-100 p-4">@if($canEdit)<form action="{{ $actionUrl('income-save') }}" method="post" data-budget-action data-budget-autosave class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value="{{ $income->id }}"><label><span class="label">Source</span><input class="input input-sm w-full" name="name" value="{{ $income->name }}" required maxlength="100"></label><label><span class="label">Expected ({{ $currencySymbol }})</span><input class="input input-sm w-full" type="number" name="expected_amount" value="{{ $amount($income->expected_cents) }}" step="0.01" min="0" required></label><label><span class="label">Expected date &middot; optional</span><input class="input input-sm w-full" type="date" name="expected_date" min="{{ $period->start_date->toDateString() }}" max="{{ $period->end_date->toDateString() }}" value="{{ $income->expected_date?->toDateString() }}"></label><label><span class="label">Received ({{ $currencySymbol }})</span><input class="input input-sm w-full" type="number" name="received_amount" value="{{ $amount($income->received_cents) }}" step="0.01" min="0" required></label><label><span class="label">Date received</span><input class="input input-sm w-full" type="date" name="received_date" min="{{ $period->start_date->toDateString() }}" max="{{ $period->end_date->toDateString() }}" value="{{ $income->received_date?->toDateString() }}"></label><noscript><button type="submit" class="btn btn-sm">Save income</button></noscript></form><form method="post" action="{{ $actionUrl('income-remove') }}" data-budget-action data-confirm="Remove this income source and its received amount from this period?" class="mt-2">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value="{{ $income->id }}"><button class="btn btn-xs btn-ghost" type="submit">Remove source</button></form>@else<p>{{ $income->name }} · Expected {{ $money($income->expected_cents) }} · Received {{ $money($income->received_cents) }}</p>@endif</div>@empty<p class="rounded-sm border border-dashed border-base-300 p-6 text-sm opacity-70">Add your salary or another income source to start allocating money.</p>@endforelse</section>
</div>
