<div class="space-y-8">
    <header class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-xl font-semibold">Recurring expenses</h3><p class="mt-1 text-sm opacity-60">Plan regular bills and record them quickly, with suggestions based on your actual payment history.</p></div>@if($canEdit)<button class="btn btn-primary btn-sm" type="button" data-open-dialog="budget-recurring-edit" data-new-recurring>Add recurring expense</button>@endif</header>
    <section class="space-y-4" aria-labelledby="budget-recurring-due-title"><h4 id="budget-recurring-due-title" class="font-semibold">Scheduled in this period</h4>
    @if($canEdit && $period->end_date->lt(now()->startOfDay()) && $recurringExpenses->isNotEmpty())<form class="mt-3" method="post" action="{{ $actionUrl('recurring-load') }}" data-budget-action>@csrf<input type="hidden" name="version" value="{{ $period->version }}"><button type="submit" class="btn btn-sm btn-outline">Load / update past occurrences</button></form><p class="mt-2 text-xs">Loads schedules for this past period so you can record old payments or link existing bills. Recorded payments are preserved; unpaid forecasts use the current schedules.</p>@endif
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        @forelse($recurringCharges as $charge)
        <article class="rounded-sm border border-base-300 bg-base-100 p-5 space-y-3"><div class="flex items-start justify-between gap-3"><div><h5 class="font-semibold">{{ $charge->name }}</h5><p class="text-xs opacity-60 mt-1">{{ $charge->scheduled_date->format('d M Y') }} &middot; {{ $categories->firstWhere('id', $charge->budget_category_id)?->name ?? 'Other' }}</p></div><span class="badge badge-outline">{{ $charge->transaction ? 'Paid' : 'Unpaid' }}</span></div>
            @if($charge->transaction)<p class="text-sm text-success">{{ $money($charge->transaction->amount_cents) }} recorded on {{ $charge->transaction->date->format('d M Y') }}</p>@else<p class="text-2xl font-semibold">{{ $money($charge->amount_cents) }}</p><p class="text-xs opacity-60">{{ $charge->history_payments > 0 ? 'Average of '.$charge->history_payments.' payments across '.$charge->history_months.' of the preceding three completed months.' : 'Starting estimate. No payments recorded in the prior three completed months.' }}</p>@if($canEdit && $charge->is_current)<button class="btn btn-sm btn-outline" type="button" data-open-dialog="budget-recurring-payment" data-pay-recurring="{{ $charge->id }}" data-charge-amount="{{ $amount($charge->amount_cents) }}" data-charge-name="{{ $charge->name }}">Record payment</button>@endif @endif
        </article>
        @empty<div class="rounded-sm border border-dashed border-base-300 p-6 text-sm opacity-60 md:col-span-2 xl:col-span-3">No recurring payments scheduled inside this period's dates.</div>@endforelse
    </div></section>
    <section class="space-y-4" aria-labelledby="budget-recurring-schedules-title"><h4 id="budget-recurring-schedules-title" class="font-semibold">Your schedules</h4><div class="space-y-3">
        @forelse($recurringExpenses as $expense)
        @php $recurringCategory = $categories->firstWhere('name', $expense->category_name) ?? $categories->firstWhere('kind', 'other'); @endphp
        <article class="rounded-sm border border-base-300 bg-base-100 p-4 flex flex-wrap items-center justify-between gap-3"><div><h5 class="font-semibold">{{ $expense->name }} <span class="badge badge-sm badge-ghost">{{ $expense->is_active ? 'Active' : 'Paused' }}</span></h5><p class="mt-1 text-xs opacity-60">{{ $expense->billing_frequency->label() }} &middot; {{ $expense->category_name }} &middot; From {{ $expense->start_date->format('d M Y') }}@if($expense->end_date) to {{ $expense->end_date->format('d M Y') }} @endif</p></div>
        @if($canEdit)<div class="flex gap-2"><button class="btn btn-sm btn-ghost" type="button" data-open-dialog="budget-recurring-edit" data-edit-recurring="{{ json_encode(['id' => $expense->id, 'name' => $expense->name, 'category_id' => $recurringCategory?->id, 'amount' => $amount($expense->amount_cents), 'billing_frequency' => $expense->billing_frequency->value, 'start_date' => $expense->start_date->toDateString(), 'end_date' => $expense->end_date?->toDateString(), 'is_active' => $expense->is_active ? 1 : 0]) }}">Edit</button><form action="{{ $actionUrl('recurring-remove') }}" method="post" data-budget-action data-confirm="Remove the {{ $expense->name }} recurring schedule? Future unpaid forecasts will be removed. Recorded payments are kept." data-confirm-title="Remove recurring expense?" data-confirm-label="Remove schedule">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value="{{ $expense->id }}"><button class="btn btn-sm btn-ghost text-error" type="submit">Remove</button></form></div>@endif
        </article>
        @empty<p class="text-sm opacity-60">Start with regular costs such as rent, electricity, groceries, or transport. Schedules generate forecasts and suggestions, not automatic payments.</p>@endforelse
    </div></section>
</div>
