    <section data-budget-live="summary" class="space-y-3" aria-label="Budget summary">
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <div class="card border border-base-300 bg-base-100"><div class="card-body"><p class="text-sm opacity-70">Expected income</p><p class="text-2xl font-bold">{{ $money($totals['expected']) }}</p><p class="text-xs opacity-60">Received: {{ $money($totals['received']) }}</p></div></div>
            <div class="card border border-base-300 bg-base-100"><div class="card-body"><p class="text-sm opacity-70">Planned spending</p><p class="text-2xl font-bold">{{ $money($totals['planned']) }}</p><p @class(['text-xs', 'text-error' => $totals['unallocated'] < 0, 'opacity-60' => $totals['unallocated'] >= 0])>{{ $totals['unallocated'] < 0 ? 'Overplanned by ' : 'Unallocated: ' }}{{ $money(abs($totals['unallocated'])) }}</p></div></div>
            <div class="card border border-base-300 bg-base-100"><div class="card-body"><p class="text-sm opacity-70">Spent so far</p><p class="text-2xl font-bold">{{ $money($totals['spent']) }}</p><p class="text-xs opacity-60">Unpaid scheduled expenses: {{ $money($totals['upcoming']) }}</p></div></div>
            <div class="card border border-primary/30 bg-primary/5"><div class="card-body"><p class="text-sm opacity-70">Expected money left</p><p @class(['text-2xl font-bold', 'text-error' => $totals['remaining'] < 0])>{{ $money($totals['remaining']) }}</p><p class="text-xs opacity-60">After unpaid charges: {{ $money($totals['after_commitments']) }}</p></div></div>
        </div>
        <p class="text-xs opacity-60">Budget estimates, not your bank balance. Received income minus recorded spending is {{ $money($totals['received'] - $totals['spent']) }}. <button type="button" class="link" data-scroll-to="budget-transactions">Review expenses</button> · <button type="button" class="link" data-scroll-to="budget-incomes">Review income</button></p>
    </section>
    @if($subscriptionChanges)<div class="alert alert-info text-sm"><div><p class="font-semibold">{{ collect($subscriptionChanges)->contains(fn (string $change): bool => str_contains($change, 'recurring forecast')) ? 'Scheduled expense forecast updated' : 'Subscription forecast updated' }}</p><ul>@foreach(array_slice($subscriptionChanges, 0, 5) as $change)<li>{{ $change }}</li>@endforeach</ul><p>Recorded payments are preserved. Unpaid forecasts reflect your current schedules.</p></div></div>@endif
