@if($period === null)
<div class="card border border-dashed border-base-300 bg-base-100"><div class="card-body items-center py-14 text-center"><h2 class="card-title">Your first budget starts here</h2><p>Choose your dates and income. Add expenses as you go.</p><button class="btn btn-primary mt-3" type="button" data-open-dialog="new-budget">Create my first budget</button></div></div>
@else
@php
    $money = fn (int $cents): string => 'ZAR '.number_format($cents / 100, 2);
    $amount = fn (int $cents): string => number_format($cents / 100, 2, '.', '');
    $actionUrl = fn (string $action): string => route('budgets.action', ['period' => $period, 'action' => $action]);
    $defaultDate = max($period->start_date->toDateString(), min(now()->toDateString(), $period->end_date->toDateString()));
    $budgetTabs = ['overview' => 'Overview', 'review' => 'Period review', 'plan' => 'Plan', 'expenses' => 'Expenses', 'subscriptions' => 'Subscriptions', 'recurring' => 'Recurring expenses', 'notifications' => 'Notifications'];
    $requestedBudgetTab = request('tab');
    $activeBudgetTab = is_string($requestedBudgetTab) && array_key_exists($requestedBudgetTab, $budgetTabs) ? $requestedBudgetTab : 'overview';
@endphp
<div class="space-y-6" data-budget-version="{{ $period->version }}" data-budget-period="{{ $period->id }}" data-budget-undo-url="{{ $actionUrl('expense-restore') }}">
    <div class="flex flex-wrap items-end justify-between gap-4">
        <form action="{{ route('budgets.index') }}" method="get" data-budget-navigation><label class="label" for="budget-period-select">Budget and period</label><select id="budget-period-select" name="period" class="select w-full max-w-xl">@foreach($budgets as $visibleBudget)<optgroup label="{{ $visibleBudget->name }} ({{ $visibleBudget->scope }})">@foreach($visibleBudget->periods as $visiblePeriod)<option value="{{ $visiblePeriod->id }}" @selected($visiblePeriod->id === $period->id)>{{ $visiblePeriod->name }}: {{ $visiblePeriod->start_date->format('d M Y') }} - {{ $visiblePeriod->end_date->format('d M Y') }}</option>@endforeach</optgroup>@endforeach</select><noscript><button class="btn btn-sm" type="submit">Open period</button></noscript></form>
        <div class="flex flex-wrap gap-2"><span class="badge badge-outline">{{ $budget->scope === 'household' ? 'Shared household budget' : 'Private personal budget' }}</span><span class="badge badge-outline">{{ $isOwner ? 'Owner' : ($canEdit ? 'Editor' : 'View only') }}</span></div>
    </div>
    <div class="flex flex-wrap items-center justify-between gap-4">
        <div><h2 class="text-2xl font-semibold break-words">{{ $budget->name }}</h2><p class="mt-1 text-sm opacity-60">{{ $period->name }} &middot; {{ $period->start_date->format('d M Y') }} - {{ $period->end_date->format('d M Y') }} &middot; Both dates included</p></div>
        @if($canEdit || auth()->user()->can('delete', $budget))
        <div class="flex items-center gap-2">
            @if($canEdit)<button class="btn btn-primary" data-open-dialog="budget-expense" data-new-expense type="button">+ Add expense</button>@endif
            <details class="dropdown dropdown-end"><summary class="btn btn-outline inline-flex items-center gap-2" aria-label="Budget options">Options <x-lucide-chevron-down class="size-4 shrink-0" aria-hidden="true" /></summary><ul class="menu dropdown-content z-10 mt-2 w-56 rounded-sm border border-base-300 bg-base-100 p-2 shadow-lg">
                @if($canEdit)
                <li><button data-open-dialog="budget-rename" type="button">Rename budget</button></li>
                <li><button data-open-dialog="budget-dates" type="button">Change dates</button></li>
                <li><button data-open-dialog="budget-copy" type="button">Copy to next period</button></li>
                @if($isOwner)<li><button data-open-dialog="budget-sharing" type="button">{{ $budget->scope === 'household' ? 'Sharing & settings' : 'Settings' }}</button></li>@endif
                @endif
                @can('delete', $budget)
                <li><form method="post" action="{{ route('admin.budgets.destroy', $budget) }}" data-confirm="Permanently delete {{ $budget->name }} and all its periods, groups, categories, income, and expenses? This cannot be undone. The owner's subscriptions are kept." data-confirm-title="Delete budget?" data-confirm-label="Delete budget">@csrf @method('DELETE')<button class="text-error" type="submit">Delete budget</button></form></li>
                @endcan
            </ul></details>
        </div>
        @endif
    </div>
    <div class="overflow-x-auto border-b border-base-300">
        <div class="tabs tabs-border w-max min-w-full" role="tablist" aria-label="Budget views">
            @foreach($budgetTabs as $tab => $label)
            <button type="button" id="budget-tab-{{ $tab }}" @class(['tab gap-2 px-5', 'tab-active' => $tab === $activeBudgetTab]) role="tab" aria-controls="budget-panel-{{ $tab }}" aria-selected="{{ $tab === $activeBudgetTab ? 'true' : 'false' }}" tabindex="{{ $tab === $activeBudgetTab ? '0' : '-1' }}" data-budget-tab="{{ $tab }}">{{ $label }}@if($tab === 'expenses')<span class="badge badge-sm badge-ghost">{{ $transactions->count() }}</span>@endif</button>
            @endforeach
        </div>
    </div>
    @foreach(array_keys($budgetTabs) as $tab)
    <div id="budget-panel-{{ $tab }}" role="tabpanel" aria-labelledby="budget-tab-{{ $tab }}" tabindex="0" data-budget-panel="{{ $tab }}" @if($tab !== $activeBudgetTab) hidden @endif>
        @include('budgets.'.($tab === 'subscriptions' ? 'charges' : $tab))
    </div>
    @endforeach
    <noscript><style>[data-budget-panel][hidden] { display: block; }</style><p class="text-sm opacity-60">Enable JavaScript to switch between budget tabs.</p></noscript>
    @if($canEdit)
    <dialog id="budget-recurring-edit" class="modal" aria-labelledby="budget-recurring-edit-title"><div class="modal-box max-w-xl"><h3 id="budget-recurring-edit-title" class="text-xl font-bold">Recurring expense</h3><form method="post" action="{{ $actionUrl('recurring-save') }}" data-budget-action class="mt-5 space-y-4">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value=""><label class="block"><span class="label">Name</span><input class="input w-full" name="name" required maxlength="100" placeholder="e.g. Electricity"></label><div class="grid gap-4 sm:grid-cols-2"><label><span class="label">Category</span><select class="select w-full" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label><span class="label">Frequency</span><select class="select w-full" name="billing_frequency">@foreach(\App\BillingFrequency::cases() as $frequency)<option value="{{ $frequency->value }}" @selected($frequency === \App\BillingFrequency::Monthly)>{{ $frequency->label() }}</option>@endforeach</select></label></div><label class="block"><span class="label">Starting estimate per payment (ZAR)</span><input class="input w-full" type="number" name="amount" step="0.01" min="0.01" required></label><p class="text-xs opacity-60">Once there is history, we suggest the average recorded payment from the previous three completed calendar months. Months with no payments are excluded. Future forecasts use the latest completed months available.</p><div class="grid gap-4 sm:grid-cols-2"><label><span class="label">First scheduled payment</span><input class="input w-full" type="date" name="start_date" value="{{ $defaultDate }}" required></label><label><span class="label">Last scheduled payment (optional)</span><input class="input w-full" type="date" name="end_date"></label></div><label class="block"><span class="label">Schedule status</span><select class="select w-full" name="is_active"><option value="1">Active</option><option value="0">Paused</option></select></label><p class="text-xs opacity-60">Schedules belong to this budget across all its periods. Category names carry into copied periods; missing categories use Other. Payments are recorded only when you confirm them.</p><div class="modal-action"><button class="btn btn-ghost" type="button" data-close-dialog>Cancel</button><button class="btn btn-primary" type="submit">Save schedule</button></div></form></div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>
    <dialog id="budget-rename" class="modal" aria-labelledby="budget-rename-title"><div class="modal-box"><h3 id="budget-rename-title" class="text-xl font-bold">Rename budget</h3><form method="post" action="{{ $actionUrl('budget-rename') }}" data-budget-action class="mt-5 space-y-4">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><label class="block"><span class="label">Budget name</span><input class="input w-full" name="name" value="{{ $budget->name }}" required maxlength="100"></label><p class="text-sm opacity-60">This changes the name of the whole budget. Individual period names stay the same.</p><div class="modal-action"><button class="btn btn-ghost" type="button" data-close-dialog>Cancel</button><button class="btn btn-primary" type="submit">Save name</button></div></form></div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>
    <dialog id="budget-group" class="modal" aria-labelledby="budget-group-title"><div class="modal-box"><h3 id="budget-group-title" class="text-xl font-bold">Create a category group</h3><form action="{{ $actionUrl('group-save') }}" method="post" data-budget-action class="mt-5 space-y-4">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><label class="block"><span class="label">Group name</span><input class="input w-full" name="name" required maxlength="100" placeholder="e.g. Needs"></label><label class="block"><span class="label">Limit (% of expected income, optional)</span><input class="input w-full" name="percentage" type="number" min="0" max="100" step="0.01" placeholder="e.g. 50"></label><p class="text-xs opacity-60">A 50% limit on {{ $money($totals['expected']) }} expected income is {{ $money((int) round($totals['expected'] / 2)) }}. Limits guide your plan; they do not allocate category money or block recording expenses.</p><div class="modal-action"><button class="btn btn-ghost" type="button" data-close-dialog>Cancel</button><button class="btn btn-primary" type="submit">Create group</button></div></form></div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>
    @foreach(['expense' => 'Add or edit expense', 'income' => 'Add income source', 'category' => 'Add category', 'payment' => 'Record subscription payment', 'transfer' => 'Move money between categories', 'recurring-payment' => 'Record recurring payment'] as $panel => $title)
    @php $panelAction = ['expense' => 'expense-save', 'income' => 'income-save', 'category' => 'category-save', 'payment' => 'commitment-pay', 'transfer' => 'transfer', 'recurring-payment' => 'recurring-pay'][$panel]; @endphp
    <dialog id="budget-{{ $panel }}" class="modal" aria-labelledby="budget-{{ $panel }}-title"><div class="modal-box"><h3 class="text-xl font-bold" id="budget-{{ $panel }}-title">{{ $title }}</h3><form method="post" action="{{ $actionUrl($panelAction) }}" data-budget-action class="mt-5 space-y-4">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="id" value="">
        @if(in_array($panel, ['income', 'category'], true))<label class="block"><span class="label">Name</span><input class="input w-full" name="name" required maxlength="100"></label>@endif
        @if($panel === 'income')<label class="block"><span class="label">Expected income (ZAR)</span><input class="input w-full" name="expected_amount" type="number" step="0.01" min="0" required></label><label class="block"><span class="label">Expected income date &middot; optional</span><input class="input w-full" name="expected_date" type="date" min="{{ $period->start_date->toDateString() }}" max="{{ $period->end_date->toDateString() }}"></label><label class="block"><span class="label">Received income (ZAR)</span><input class="input w-full" name="received_amount" type="number" step="0.01" min="0" value="0" required></label><label class="block"><span class="label">Date received (if any)</span><input class="input w-full" name="received_date" type="date" min="{{ $period->start_date->toDateString() }}" max="{{ $period->end_date->toDateString() }}"></label>@else<label class="block"><span class="label">Amount (ZAR)</span><input class="input w-full" name="amount" type="number" step="0.01" min="{{ $panel === 'category' ? '0' : '0.01' }}" required></label>@endif
        @if($panel === 'expense')<label class="block"><span class="label">Recurring occurrence (optional)</span><select class="select w-full" name="recurring_charge_id" data-recurring-occurrence><option value="">Regular expense</option>@foreach($recurringCharges as $charge)<option value="{{ $charge->id }}" data-paid-transaction="{{ $charge->transaction?->id }}">{{ $charge->name }} - {{ $charge->scheduled_date->format('d M Y') }}</option>@endforeach</select><span class="mt-1 block text-xs opacity-60">Link an existing bill to its occurrence to include it in the average without creating another expense.</span></label><label class="block"><span class="label">Category</span><select class="select w-full" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label class="block"><span class="label">Description (optional)</span><input class="input w-full" name="description" maxlength="255"></label><p class="hidden text-xs opacity-60" data-linked-expense-hint>Linked subscription payments remain in the Subscriptions category.</p>@endif
        @if(in_array($panel, ['expense', 'payment', 'recurring-payment'], true))<label class="block"><span class="label">Payment date</span><input class="input w-full" name="date" type="date" value="{{ $defaultDate }}" min="{{ $period->start_date->toDateString() }}" max="{{ $period->end_date->toDateString() }}" required></label>@endif
        @if(in_array($panel, ['payment', 'recurring-payment'], true))<p class="text-sm opacity-70" data-charge-label>Confirm the amount and payment date. This replaces the unpaid forecast with one recorded expense.</p>@endif
        @if($panel === 'transfer')<div class="grid gap-4 sm:grid-cols-2">@foreach(['from_id' => 'From category', 'to_id' => 'To category'] as $field => $label)<label><span class="label">{{ $label }}</span><select class="select w-full" name="{{ $field }}" required>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label>@endforeach</div><p class="text-xs opacity-60">Total allocation stays the same. Moving money from an automatic subscription limit makes that limit manual.</p>@endif
        <div class="modal-action"><button class="btn btn-ghost" type="button" data-close-dialog>Cancel</button><button class="btn btn-primary" type="submit">Save</button></div>
    </form></div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>
    @endforeach
    <dialog id="budget-copy" class="modal" aria-labelledby="budget-copy-title"><div class="modal-box"><h3 id="budget-copy-title" class="text-xl font-bold">Copy your plan to the next period</h3><form method="post" action="{{ route('budgets.periods.store', $budget) }}" data-budget-action class="mt-5 space-y-4">@csrf<input type="hidden" name="copy_from" value="{{ $period->id }}"><input type="hidden" name="expected_income" value="0"><label class="block"><span class="label">Period name</span><input class="input w-full" name="name" value="Next period" required maxlength="100"></label><div class="grid gap-4 sm:grid-cols-2"><label><span class="label">Start date</span><input class="input w-full" name="start_date" type="date" value="{{ $nextStart }}" required></label><label><span class="label">End date</span><input class="input w-full" name="end_date" type="date" value="{{ $nextEnd }}" required></label></div><p class="text-sm opacity-70">Copies expected income and category allocations. Recorded payments and received income start fresh. Subscription charges use the new dates. No unused allocation carries over.</p><div class="modal-action"><button type="button" class="btn btn-ghost" data-close-dialog>Cancel</button><button class="btn btn-primary" type="submit">Create next period</button></div></form></div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>
    <dialog id="budget-dates" class="modal" aria-labelledby="budget-dates-title"><div class="modal-box"><h3 id="budget-dates-title" class="text-xl font-bold">Change period dates</h3><form method="post" action="{{ $actionUrl('period-save') }}" data-budget-action data-budget-dates data-preview-url="{{ $actionUrl('period-preview') }}" class="mt-5 space-y-4">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="preview_token" value=""><label class="block"><span class="label">Period name</span><input class="input w-full" name="name" value="{{ $period->name }}" required maxlength="100"></label><div class="grid gap-4 sm:grid-cols-2"><label><span class="label">Start date</span><input class="input w-full" name="start_date" type="date" value="{{ $period->start_date->toDateString() }}" required></label><label><span class="label">End date</span><input class="input w-full" name="end_date" type="date" value="{{ $period->end_date->toDateString() }}" required></label></div><button class="btn btn-outline" type="button" data-preview-dates>Preview impact</button><p class="text-sm opacity-70" data-preview-result>Preview before applying. Dates must keep all recorded expenses and received income inside the period.</p><div class="modal-action"><button type="button" class="btn btn-ghost" data-close-dialog>Cancel</button><button class="btn btn-primary" type="submit">Apply changes</button></div></form></div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>
    @endif
    @if($isOwner)
    <dialog id="budget-sharing" class="modal" aria-labelledby="budget-sharing-title"><div class="modal-box max-w-xl space-y-5"><h3 id="budget-sharing-title" class="text-xl font-bold">{{ $budget->scope === 'household' ? 'Household sharing & settings' : 'Personal budget settings' }}</h3>
        <form method="post" action="{{ $actionUrl('settings-save') }}" data-budget-action class="space-y-4">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="include_subscriptions" value="0"><label class="flex gap-3"><input class="checkbox checkbox-sm" type="checkbox" name="include_subscriptions" value="1" @checked($budget->include_subscriptions)><span class="text-sm">Include my subscription charges. In household budgets, invited viewers and editors can see these names, amounts, and dates.</span></label><label class="block"><span class="label">Repeat pay cycle</span><select class="select w-full" name="repeat_cycle">@foreach(['none' => 'Off - choose each period', 'monthly' => 'Monthly on the original start day', 'fixed_days' => 'Same number of days'] as $value => $label)<option value="{{ $value }}" @selected($budget->repeat_cycle === $value)>{{ $label }}</option>@endforeach</select></label><button class="btn btn-primary" type="submit">Save settings</button></form>
        @if($budget->scope === 'household')<p class="text-sm opacity-70">Viewers can read. Editors can change income, spending, categories, and periods. Only you can change sharing. App admin roles do not grant financial access.</p><ul class="space-y-2">@foreach($members as $member)<li class="flex items-center justify-between gap-3"><span>{{ $member->name }} · {{ $member->pivot->role }}</span><form method="post" action="{{ $actionUrl('member-save') }}" data-budget-action data-confirm="Remove {{ $member->name }} from this household budget? They will lose access. Recorded financial data will be kept." data-confirm-title="Remove budget access?" data-confirm-label="Remove access">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><input type="hidden" name="user_id" value="{{ $member->id }}"><input type="hidden" name="role" value="remove"><button class="btn btn-xs btn-ghost" type="submit">Remove access</button></form></li>@endforeach</ul><form method="post" action="{{ $actionUrl('member-save') }}" data-budget-action class="space-y-3">@csrf<input type="hidden" name="version" value="{{ $period->version }}"><label class="block"><span class="label">Existing app user</span><select class="select w-full" name="user_id" required>@foreach($availableUsers as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></label><label class="block"><span class="label">Budget access</span><select class="select w-full" name="role"><option value="viewer">Viewer</option><option value="editor">Editor</option></select></label><button class="btn btn-outline" type="submit">Assign budget access</button></form>@else<p class="text-sm opacity-70">This budget is private to you, including from other administrators.</p>@endif
        <div class="modal-action"><button type="button" class="btn btn-ghost" data-close-dialog>Done</button></div>
    </div><form method="dialog" class="modal-backdrop"><button>Close</button></form></dialog>
    @endif
</div>
@endif
