<section class="rounded-sm border border-base-300 bg-base-100 p-3" aria-labelledby="dashboard-budget-pace-title" data-dashboard-budget-pace>
    <div class="flex flex-wrap items-center justify-between gap-2"><div><h2 id="dashboard-budget-pace-title" class="flex items-center gap-1.5 text-sm font-semibold"><x-lucide-chart-line class="size-3.5 text-primary" aria-hidden="true" />Current-period spending pace</h2><p class="text-[10px] opacity-60">Recorded spending compared with a straight-line budget pace.</p></div><label class="block"><span class="sr-only">Budget for spending pace</span><select class="select select-xs max-w-52" data-pace-budget>@foreach($budgetOverview['cards'] as $card)<option value="{{ $card['budget']->id }}">{{ $card['budget']->name }}</option>@endforeach</select></label></div>
    @if($budgetOverview['cards']->isEmpty())
        <p class="mt-3 text-xs opacity-65">A chart appears when a budget period is in progress. <a class="link link-primary" href="{{ route('budgets.index') }}">View budgets</a>.</p>
    @else
        <div class="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px]"><span class="inline-flex items-center gap-1.5"><span class="h-0.5 w-5 bg-orange-600" aria-hidden="true"></span>Recorded spending</span><span class="inline-flex items-center gap-1.5"><span class="h-0.5 w-5 border-t border-dashed border-primary" aria-hidden="true"></span>Budget pace</span><span class="inline-flex items-center gap-1.5"><span class="h-0.5 w-5 border-t border-dotted border-success" aria-hidden="true"></span>Income received</span></div>
        <div class="mt-1 w-full overflow-x-auto" role="region" aria-label="Current-period spending pace chart" tabindex="0" data-pace-chart></div>
        <div class="flex flex-wrap items-center justify-between gap-2 text-[10px] opacity-65"><span data-pace-summary></span><a class="link link-primary" data-pace-link>Review period</a></div>
        <script type="application/json" data-pace-data>{!! json_encode($budgetOverview['cards']->map(fn (array $card): array => ['id' => $card['budget']->id, 'name' => $card['budget']->name, 'start' => $card['period']->start_date->toDateString(), 'end' => $card['period']->end_date->toDateString(), 'planned' => $card['totals']['planned'], 'received' => $card['totals']['received'], 'spent' => $card['totals']['spent'], 'points' => $card['dailyPace'], 'url' => $card['url']])->values()->all(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR) !!}</script>
    @endif
</section>
