@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
<div class="mx-auto max-w-7xl space-y-5" data-dashboard-customization data-layout-url="{{ route('dashboard.layout.update') }}" data-layout-token="{{ csrf_token() }}">
    <header class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-bold">Welcome, {{ auth()->user()->name }}</h1><p class="mt-2 opacity-70">Your space for managing individual and household finances.</p></div><button class="btn btn-outline" type="button" data-layout-edit aria-expanded="false" aria-controls="dashboard-customize">Customize dashboard <x-lucide-sliders-horizontal class="size-4" /></button></header>
    <p class="text-sm opacity-65" data-layout-status role="status" aria-live="polite">{{ session('status') }}</p>
    <section id="dashboard-customize" class="rounded-sm border border-primary/30 bg-base-100 p-4" data-layout-panel hidden>
        <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-semibold">Make this dashboard yours</h2><p class="mt-1 text-xs opacity-65">Choose widgets below. Drag a tile's handle or use its arrow buttons to reorder it. Resize with its corner handle or size menus. Small screens stack tiles in your chosen order.</p></div><div class="flex flex-wrap gap-2"><button class="btn btn-primary btn-sm" type="button" data-layout-save>Save layout</button><button class="btn btn-ghost btn-sm" type="button" data-layout-cancel>Cancel</button><button class="btn btn-outline btn-sm" type="button" data-layout-reset>Reset to default</button></div></div>
        <fieldset class="mt-4"><legend class="text-xs font-medium">Visible widgets</legend><div class="mt-2 flex flex-wrap gap-x-5 gap-y-3">@foreach($dashboardLayout as $widget)<label class="flex items-center gap-2 text-sm"><input type="checkbox" class="checkbox checkbox-sm" data-layout-visible="{{ $widget['id'] }}" @checked($widget['visible'])>{{ $dashboardWidgets[$widget['id']] }}</label>@endforeach</div></fieldset>
    </section>
    <div class="rounded-sm border border-dashed border-base-300 bg-base-100 p-8 text-center" data-layout-empty @if(collect($dashboardLayout)->contains('visible', true)) hidden @endif><p class="font-semibold">Your dashboard is clear</p><p class="mt-1 text-sm opacity-65">Use Customize dashboard to choose the widgets you want to see.</p></div>
    <div class="dashboard-widget-grid" data-layout-grid>
        @foreach($dashboardLayout as $widget)
            <article class="dashboard-widget min-w-0" data-layout-widget="{{ $widget['id'] }}" data-width="{{ $widget['width'] }}" data-height="{{ $widget['height'] }}" @if(! $widget['visible']) hidden @endif>
                <div class="dashboard-widget-toolbar flex flex-wrap items-center justify-between gap-2 rounded-t-sm border border-base-300 bg-base-100 p-2" data-layout-toolbar hidden>
                    <div class="flex min-w-0 items-center gap-1"><button class="btn btn-ghost btn-xs cursor-grab" type="button" draggable="true" data-layout-drag aria-label="Drag {{ $dashboardWidgets[$widget['id']] }}"><x-lucide-grip-vertical class="size-4" /></button><span class="text-xs font-semibold">{{ $dashboardWidgets[$widget['id']] }}</span></div>
                    <div class="flex flex-wrap items-center gap-1"><button type="button" class="btn btn-ghost btn-xs" data-layout-move="up" aria-label="Move {{ $dashboardWidgets[$widget['id']] }} earlier"><x-lucide-arrow-up class="size-3" /></button><button type="button" class="btn btn-ghost btn-xs" data-layout-move="down" aria-label="Move {{ $dashboardWidgets[$widget['id']] }} later"><x-lucide-arrow-down class="size-3" /></button><label><span class="sr-only">{{ $dashboardWidgets[$widget['id']] }} width</span><select class="select select-xs" data-layout-width>@foreach(['small' => 'Small', 'medium' => 'Medium', 'wide' => 'Full width'] as $value => $label)<option value="{{ $value }}" @selected($widget['width'] === $value)>{{ $label }}</option>@endforeach</select></label><label><span class="sr-only">{{ $dashboardWidgets[$widget['id']] }} height</span><select class="select select-xs" data-layout-height>@foreach(['auto' => 'Auto height', 'compact' => 'Compact', 'regular' => 'Regular', 'tall' => 'Tall'] as $value => $label)<option value="{{ $value }}" @selected($widget['height'] === $value)>{{ $label }}</option>@endforeach</select></label><button class="btn btn-ghost btn-xs" type="button" data-layout-hide aria-label="Hide {{ $dashboardWidgets[$widget['id']] }}"><x-lucide-eye-off class="size-3.5" /></button></div>
                </div>
                <div class="dashboard-widget-body min-w-0" tabindex="0" aria-label="{{ $dashboardWidgets[$widget['id']] }} widget">@include('dashboard.'.$widget['id'])</div>
                <div class="flex justify-end rounded-b-sm border border-t-0 border-base-300 bg-base-100 px-2" data-layout-toolbar hidden><button type="button" class="btn btn-ghost btn-xs touch-none cursor-nwse-resize" data-layout-resize aria-label="Resize {{ $dashboardWidgets[$widget['id']] }}; width and height menus are also available"><x-lucide-move-diagonal-2 class="size-4" /></button></div>
            </article>
        @endforeach
    </div>
    <noscript><p class="text-sm opacity-65">Enable JavaScript to customize your dashboard. Your saved layout is still displayed.</p></noscript>
    <script type="application/json" data-layout-data>{!! json_encode($dashboardLayout, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_THROW_ON_ERROR) !!}</script>
    <script type="application/json" data-layout-defaults>{!! json_encode($dashboardDefaults, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_THROW_ON_ERROR) !!}</script>
</div>
@endsection
