<section class="rounded-sm border border-base-300 bg-base-100 p-4" aria-labelledby="dashboard-worth-title"><div class="flex flex-wrap items-center justify-between gap-2"><h2 id="dashboard-worth-title" class="text-lg font-semibold">Net worth</h2><a class="btn btn-outline" href="{{ route('net-worth.index') }}">View assets and history</a></div>
@if($netWorthOverview['assets']->isEmpty() && $netWorthOverview['debts']->isEmpty())<p class="mt-2 text-sm opacity-65">Add assets and track debts to see your overall financial position. Savings goals will not be counted twice.</p>@else
<div class="mt-3 grid gap-3 sm:grid-cols-3">@foreach(['Net worth' => $netWorthOverview['netWorth'], 'Assets' => $netWorthOverview['assetTotal'], 'Debt principal' => $netWorthOverview['debtTotal']] as $label => $value)<div><p class="text-xs opacity-60">{{ $label }}</p><p @class(['mt-1 text-xl font-semibold', 'text-error' => $label === 'Net worth' && $value < 0])>ZAR {{ number_format($value / 100, 2) }}</p></div>@endforeach</div>
@if($netWorthOverview['change'] !== null)<p class="mt-2 text-xs opacity-65">ZAR {{ number_format(abs($netWorthOverview['change']) / 100, 2) }} {{ $netWorthOverview['change'] >= 0 ? 'higher' : 'lower' }} than {{ $netWorthOverview['latest']->date->format('d M Y') }} snapshot.</p>@endif
@if($netWorthOverview['snapshots']->isNotEmpty())<div class="mt-3">@include('net-worth.chart', ['chartSnapshots' => $netWorthOverview['snapshots']->take(-6), 'chartId' => 'dashboard-net-worth', 'compact' => true])</div>@else<p class="mt-3 text-xs opacity-65"><a class="link" href="{{ route('net-worth.index') }}">Save your first snapshot</a> to begin tracking net worth over time.</p>@endif
@if($netWorthOverview['stale'] > 0)<p class="mt-2 text-xs text-warning">{{ $netWorthOverview['stale'] }} assets have older valuations. <a class="link" href="{{ route('net-worth.index', ['tab' => 'assets']) }}">Refresh their values</a>.</p>@endif
<div class="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-sm bg-base-200/60 p-3"><div class="text-xs"><p><span class="opacity-60">Unreserved cash:</span> ZAR {{ number_format($liquidityOverview['free'] / 100, 2) }} / <span class="opacity-60">Emergency runway:</span> {{ $liquidityOverview['runway'] === null ? 'Set up reserves and essentials' : $liquidityOverview['runway'].' months' }}</p>@if($liquidityOverview['unknown'] > 0)<p class="mt-1 text-warning">Classify access for {{ $liquidityOverview['unknown'] }} assets to complete the cash picture.</p>@elseif($liquidityOverview['cashGap'] > 0)<p class="mt-1 text-warning">Forecast cash gap: ZAR {{ number_format($liquidityOverview['cashGap'] / 100, 2) }} on {{ \Carbon\CarbonImmutable::parse($liquidityOverview['lowest']['date'])->format('d M') }}. Check assumptions and upcoming payments.</p>@endif</div><a class="btn btn-outline" href="{{ route('net-worth.index', ['tab' => 'liquidity']) }}">Plan cash flow</a></div>
<p class="mt-2 text-xs opacity-60">Latest recorded asset values minus tracked debt principal. Your records only.</p>
@endif</section>
