@extends('layouts.app')
@section('title', 'Net worth')
@section('content')
@php
    $money = fn (int $cents): string => $currencyPrefix.number_format($cents / 100, 2);
    $amount = fn (int $cents): string => number_format($cents / 100, 2, '.', '');
    $kinds = ['bank' => 'Bank / cash', 'investment' => 'Investments', 'property' => 'Property', 'vehicle' => 'Vehicles', 'other' => 'Other assets'];
    $tab = in_array(request('tab'), ['assets', 'liquidity', 'history'], true) ? request('tab') : 'overview';
@endphp
<div class="mx-auto max-w-7xl space-y-4" data-net-worth-page>
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold">Net worth</h1><p class="mt-1 text-sm opacity-65">See what you own, what you owe, and how that changes.</p></div><div class="flex gap-2"><button class="btn btn-outline" type="button" data-worth-snapshot>Save snapshot</button><button class="btn btn-primary" type="button" data-asset-new>Add asset <x-lucide-plus class="size-4" /></button></div></div>
    @if(session('status'))<div class="alert alert-success text-sm" role="status">{{ session('status') }}@if(session('undo_asset'))<form method="post" action="{{ route('net-worth.assets.restore', session('undo_asset')) }}">@csrf<button class="btn btn-ghost">Undo</button></form>@elseif(session('undo_valuation'))<form method="post" action="{{ route('net-worth.values.restore', session('undo_valuation')) }}">@csrf<button class="btn btn-ghost">Undo</button></form>@elseif(session('undo_reserve'))<form method="post" action="{{ route('liquidity.reserves.restore', session('undo_reserve')) }}">@csrf<button class="btn btn-ghost">Undo</button></form>@elseif(session('undo_snapshot'))<form method="post" action="{{ route('net-worth.snapshots.restore', session('undo_snapshot')) }}">@csrf<button class="btn btn-ghost">Undo</button></form>@endif</div>@endif
    @if($errors->any())<div class="alert alert-error text-sm" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <nav class="tabs tabs-border" aria-label="Net worth sections">@foreach(['overview' => 'Overview', 'assets' => 'Assets', 'liquidity' => 'Liquidity', 'history' => 'History'] as $name => $label)<a @class(['tab', 'tab-active' => $tab === $name]) href="{{ route('net-worth.index', ['tab' => $name]) }}" @if($tab === $name) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
    @if($tab === 'overview')
        <div class="grid gap-3 sm:grid-cols-3">@foreach(['Net worth' => $netWorth, 'Total assets' => $assetTotal, 'Tracked debt principal' => $debtTotal] as $label => $value)<div class="rounded-sm border border-base-300 bg-base-100 p-4"><p class="text-xs opacity-60">{{ $label }}</p><p @class(['mt-1 text-2xl font-semibold', 'text-error' => $label === 'Net worth' && $value < 0])>{{ $money($value) }}</p>@if($label === 'Net worth')<p class="mt-1 text-xs opacity-60">Assets minus debts</p>@endif</div>@endforeach</div>
        @if($latest)<p class="text-xs opacity-65">{{ $money(abs($change)) }} {{ $change >= 0 ? 'higher' : 'lower' }} than your last snapshot on {{ $latest->date->format('d M Y') }}. Live values reflect your latest records.</p>@endif
        @if($stale > 0)<div class="flex flex-wrap items-center justify-between gap-2 rounded-sm bg-warning/10 p-3 text-xs"><p>{{ $stale }} assets have valuations more than 30 days old. Refresh them for a clearer picture.</p><a class="btn btn-ghost" href="{{ route('net-worth.index', ['tab' => 'assets']) }}">Update values</a></div>@endif
        <section class="rounded-sm border border-base-300 bg-base-100 p-4">@include('net-worth.chart', ['chartSnapshots' => $snapshots, 'chartId' => 'net-worth-main', 'compact' => false])</section>
        <div class="grid items-stretch gap-3 lg:grid-cols-2"><section class="rounded-sm border border-base-300 bg-base-100 p-4"><h2 class="font-semibold">What you own</h2><div class="mt-3 space-y-3">@forelse($groups as $group)<div><div class="mb-1 flex justify-between gap-2 text-xs"><span>{{ $kinds[$group['kind']] }}</span><span>{{ $money($group['amount']) }} &middot; {{ $group['share'] }}%</span></div><progress class="progress progress-primary h-2 w-full rounded-sm" value="{{ $group['share'] }}" max="100" aria-label="{{ $kinds[$group['kind']] }} share of assets"></progress></div>@empty<p class="text-sm opacity-65">Add bank balances, investments, property, or other assets to build your picture.</p><button class="btn btn-primary" type="button" data-asset-new>Add your first asset</button>@endforelse</div></section><section class="rounded-sm border border-base-300 bg-base-100 p-4"><div class="flex items-center justify-between gap-2"><h2 class="font-semibold">What you owe</h2><a class="btn btn-ghost" href="{{ route('debts.index') }}">Manage debts</a></div><div class="mt-3 space-y-2">@forelse($debts as $row)<div class="flex items-center justify-between gap-2 border-t border-base-300 pt-2 text-sm"><span>{{ $row['debt']->name }}</span><span class="font-medium">{{ $money($row['amount']) }}</span></div>@empty<p class="text-sm opacity-65">No tracked debts. Add loans or credit balances in Debt Tracking.</p>@endforelse</div><p class="mt-3 text-xs opacity-60">Debt balances use starting principal minus recorded principal payments. Accrued unpaid interest and fees are not included.</p></section></div>
        <div class="flex flex-wrap items-center justify-between gap-2 rounded-sm border border-base-300 bg-base-100 p-3 text-sm"><p><span class="opacity-60">Accessible cash:</span> {{ $money($liquidity['accessible']) }} <span class="opacity-60">/ Unreserved:</span> {{ $money($liquidity['free']) }}</p><a class="btn btn-outline" href="{{ route('net-worth.index', ['tab' => 'liquidity']) }}">Explore liquidity and cash flow</a></div>
        <p class="text-xs opacity-60">Your assets and debts only, in {{ $currencyCode }}. Savings goals earmark money already held in your assets and are not added again. Values are manually recorded estimates; no bank sync or automatic investment growth.</p>
    @elseif($tab === 'assets')
        <div class="flex flex-wrap items-end justify-between gap-2"><div><h2 class="font-semibold">Your assets</h2><p class="text-xs opacity-65">Latest recorded balances. Update values without losing older dates.</p></div><label><span class="sr-only">Filter assets</span><select class="select" data-asset-filter><option value="">All types</option>@foreach($kinds as $kind => $label)<option value="{{ $kind }}">{{ $label }}</option>@endforeach</select></label></div>
        <div class="grid items-stretch gap-3 md:grid-cols-2">@forelse($assets as $row)@php $asset = $row['asset']; $value = $row['value']; @endphp<article class="flex flex-col gap-3 rounded-sm border border-base-300 bg-base-100 p-4" data-asset-row="{{ $asset->kind }}"><div class="flex items-start justify-between gap-2"><div><h3 class="font-semibold">{{ $asset->name }}</h3><p class="mt-1 text-xs opacity-60">{{ $kinds[$asset->kind] }}{{ $asset->institution ? ' / '.$asset->institution : '' }}</p></div><button class="btn btn-ghost" type="button" data-asset-edit="{{ json_encode(['asset_id' => $asset->id, 'action' => route('net-worth.assets.update', $asset), 'name' => $asset->name, 'kind' => $asset->kind, 'institution' => $asset->institution, 'notes' => $asset->notes, 'liquidity' => $asset->liquidity, 'access_days' => $asset->access_days, 'available_date' => $asset->available_date?->toDateString(), 'withdrawal_cost' => $amount($asset->withdrawal_cost_cents), 'value_uncertain' => $asset->value_uncertain]) }}">Edit</button></div><p class="text-2xl font-semibold">{{ $money($row['amount']) }}</p><p @class(['text-xs', 'text-warning' => $row['stale'], 'opacity-60' => !$row['stale']])>Valued {{ $value->date->format('d M Y') }}{{ $row['stale'] ? ' / Refresh recommended' : '' }}</p>@if($row['amount'] !== $value->amount_cents)<p class="text-xs opacity-60">Balance includes {{ $row['amount'] > $value->amount_cents ? '+' : '-' }}{{ $money(abs($row['amount'] - $value->amount_cents)) }} in savings movements since that recorded value.</p>@endif @if($asset->notes)<p class="text-xs opacity-65">{{ $asset->notes }}</p>@endif<div class="mt-auto flex items-center justify-between gap-2"><button class="btn btn-primary" type="button" data-asset-value="{{ json_encode(['asset_id' => $asset->id, 'action' => route('net-worth.values.store', $asset), 'amount' => $amount($row['amount']), 'date' => today()->toDateString()]) }}">Update value</button><form method="post" action="{{ route('net-worth.assets.destroy', $asset) }}" data-confirm="Remove this asset from current net worth? Its valuation history and saved snapshots are kept. You can restore it." data-confirm-title="Remove asset?" data-confirm-label="Remove">@csrf @method('DELETE')<button class="btn btn-ghost text-error">Remove</button></form></div></article>@empty<div class="rounded-sm border border-dashed border-base-300 p-8 text-center md:col-span-2"><x-lucide-wallet class="mx-auto size-8 text-primary" /><h3 class="mt-3 font-semibold">Start with a bank balance</h3><p class="mt-1 text-sm opacity-65">Include savings once as an asset, even if that money funds several goals.</p><button class="btn btn-primary mt-3" type="button" data-asset-new>Add asset</button></div>@endforelse</div><p class="hidden text-xs opacity-60" data-asset-filter-empty>No assets match this type.</p>
        @if($deletedAssets->isNotEmpty())<details class="rounded-sm border border-base-300 bg-base-100 p-3"><summary class="cursor-pointer text-sm font-medium">Removed assets ({{ $deletedAssets->count() }})</summary><div class="mt-3 space-y-2">@foreach($deletedAssets as $asset)<div class="flex justify-between gap-2 text-sm"><span>{{ $asset->name }}</span><form method="post" action="{{ route('net-worth.assets.restore', $asset) }}">@csrf<button class="btn btn-ghost">Restore</button></form></div>@endforeach</div></details>@endif
    @elseif($tab === 'liquidity')
        @include('net-worth.liquidity')
    @else
        @include('net-worth.history')
    @endif
    @include('net-worth.dialogs')
    @php
        $oldAssetRow = $assets->first(fn (array $row): bool => $row['asset']->id === (int) old('asset_id'));
        $reopen = null;
        if ($errors->any() && old('form_kind') === 'value' && $oldAssetRow !== null) {
            $reopen = ['kind' => 'value', 'data' => [...old(), 'action' => route('net-worth.values.store', $oldAssetRow['asset'])]];
        } elseif ($errors->any() && old('form_kind') === 'asset') {
            $reopen = ['kind' => 'asset', 'data' => [...old(), 'action' => $oldAssetRow ? route('net-worth.assets.update', $oldAssetRow['asset']) : route('net-worth.assets.store'), 'method' => $oldAssetRow ? 'PUT' : 'POST']];
        } elseif ($errors->any() && old('form_kind') === 'snapshot') {
            $reopen = ['kind' => 'snapshot', 'data' => old()];
        }
    @endphp
    <script type="application/json" data-worth-reopen>{!! json_encode($reopen, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR) !!}</script>
</div>
@endsection
