@extends('layouts.app')
@section('title', 'Debts')
@section('content')
@php
    $money = fn (int $cents): string => 'ZAR '.number_format($cents / 100, 2);
    $amount = fn (int $cents): string => number_format($cents / 100, 2, '.', '');
    $tab = in_array(request('tab'), ['payments', 'plan'], true) ? request('tab') : 'overview';
@endphp
<div class="mx-auto max-w-7xl space-y-4" data-debts-page data-interest-url="{{ route('debts.interest', ['debt' => '__DEBT__']) }}">
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold">Debts</h1><p class="mt-1 text-sm opacity-65">Know what you owe. Give your next payment a purpose.</p></div><button class="btn btn-primary" type="button" data-debt-new>Add debt <x-lucide-plus class="size-4" /></button></div>
    @if(session('status'))<div class="alert alert-success text-sm" role="status">{{ session('status') }}@if(session('undo_payment'))<form method="post" action="{{ route('debts.payments.restore', session('undo_payment')) }}">@csrf<button class="btn btn-ghost">Undo</button></form>@endif</div>@endif
    @if($errors->any())<div class="alert alert-error text-sm" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <nav class="tabs tabs-border" aria-label="Debt sections">@foreach(['overview' => 'Overview', 'payments' => 'Payments', 'plan' => 'Payoff plan'] as $name => $label)<a @class(['tab', 'tab-active' => $name === $tab]) href="{{ route('debts.index', ['tab' => $name, 'extra' => $amount($extra)]) }}" @if($name === $tab) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
    @if($tab === 'overview')
        <div class="grid gap-3 sm:grid-cols-3">@foreach(['Tracked balance' => $total, 'Principal paid' => $paid, 'Minimum payments / month' => $minimum] as $label => $value)<div class="rounded-sm border border-base-300 bg-base-100 p-4"><p class="text-xs opacity-60">{{ $label }}</p><p class="mt-1 text-2xl font-semibold">{{ $money($value) }}</p></div>@endforeach</div>
        <p class="text-xs opacity-60">Tracked balance is starting principal minus recorded principal payments. Payment interest is estimated automatically, or you can enter the lender's actual amount. Fees and accrued unpaid interest are not added to this principal balance.</p>
        <div class="grid items-stretch gap-4 lg:grid-cols-2">
            @forelse($rows as $row)
                @php
                    $debt = $row['debt'];
                    $edit = ['debt_id' => $debt->id, 'action' => route('debts.update', $debt), 'name' => $debt->name, 'creditor' => $debt->creditor, 'balance' => $amount($debt->opening_balance_cents), 'balance_date' => $debt->balance_date->toDateString(), 'annual_rate' => $amount($debt->annual_rate_basis_points), 'minimum_payment' => $amount($debt->minimum_payment_cents), 'due_anchor' => $debt->due_anchor->toDateString(), 'budget_id' => $row['schedule']?->budget_id, 'notes' => $debt->notes, 'has_history' => $debt->payments()->withTrashed()->exists()];
                    $pay = ['action' => route('debts.payments.store', $debt), 'debt_id' => $debt->id, 'amount' => $amount(min($debt->minimum_payment_cents, $row['balance'])), 'date' => today()->toDateString()];
                @endphp
                <article class="flex flex-col gap-4 rounded-sm border border-base-300 bg-base-100 p-4">
                    <div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold">{{ $debt->name }}</h2><p class="mt-0.5 text-xs opacity-60">{{ $debt->creditor ?: 'Personal debt' }}@if($row['balance'] === 0) &middot; Paid off @endif</p></div><button class="btn btn-ghost" type="button" data-debt-edit="{{ json_encode($edit) }}">Edit</button></div>
                    <p class="text-2xl font-bold">{{ $money($row['balance']) }}</p>
                    <div class="grid grid-cols-3 gap-2 text-xs"><div><p class="opacity-60">Annual interest</p><p class="mt-1 font-medium">{{ $amount($debt->annual_rate_basis_points) }}%</p></div><div><p class="opacity-60">Minimum / month</p><p class="mt-1 font-medium">{{ $money($debt->minimum_payment_cents) }}</p></div><div><p class="opacity-60">Next scheduled date</p><p class="mt-1 font-medium">{{ $row['balance'] === 0 ? 'Complete' : $row['due']->format('d M Y') }}</p></div></div>
                    <div><div class="mb-1 flex justify-between text-xs opacity-65"><span>Principal paid</span><span>{{ $row['progress'] }}%</span></div><progress class="progress progress-primary h-2 rounded-sm w-full" value="{{ $row['progress'] }}" max="100" aria-label="{{ $debt->name }} principal payoff progress"></progress></div>
                    @if($row['credit'] > 0)<p class="text-xs text-warning">Recorded principal exceeds the starting balance by {{ $money($row['credit']) }}. Review amounts.</p>@endif
                    @if($row['unrecorded'])<p class="text-xs text-warning">An earlier scheduled date has passed without a payment recorded since. Confirm whether it was paid.</p>@endif
                    @if($row['schedule'])<p class="text-xs opacity-65">Linked to a monthly budget expense. Allocate money to its category on the budget Plan tab.</p>@endif
                    @if($debt->notes)<p class="text-xs opacity-65">{{ $debt->notes }}</p>@endif
                    <div class="mt-auto flex flex-wrap justify-between gap-2"><button class="btn btn-primary" type="button" data-debt-pay="{{ json_encode($pay) }}" @disabled($row['balance'] === 0)>Record payment</button><form method="post" action="{{ route('debts.destroy', $debt) }}" data-confirm="Delete this debt and its payment history? Its recurring schedule will be removed. Recorded budget expenses will be kept." data-confirm-title="Delete debt?" data-confirm-label="Delete debt">@csrf @method('DELETE')<button class="btn btn-ghost text-error" type="submit">Delete</button></form></div>
                </article>
            @empty
                <div class="rounded-sm border border-dashed border-base-300 p-8 text-center lg:col-span-2"><x-lucide-landmark class="mx-auto size-8 text-primary" /><h2 class="mt-3 font-semibold">Start with one debt</h2><p class="mt-1 text-sm opacity-65">Add a loan or credit balance to track payments and build a payoff plan.</p></div>
            @endforelse
        </div>
    @elseif($tab === 'payments')
        <div class="flex flex-wrap items-center justify-between gap-2"><div><h2 class="font-semibold">Payment history</h2><p class="text-xs opacity-65">Newest first. Linked budget payments appear once and update in both places.</p></div><select class="select max-w-64" aria-label="Filter payments by debt" data-debt-filter><option value="">All debts</option>@foreach($rows as $row)<option value="{{ $row['debt']->id }}" @selected((string) request('debt') === (string) $row['debt']->id)>{{ $row['debt']->name }}</option>@endforeach</select></div>
        <div class="flex flex-wrap gap-2">@foreach($rows->where('balance', '>', 0) as $row)<button class="btn btn-outline" type="button" data-debt-pay="{{ json_encode(['action' => route('debts.payments.store', $row['debt']), 'debt_id' => $row['debt']->id, 'amount' => $amount(min($row['debt']->minimum_payment_cents, $row['balance'])), 'date' => today()->toDateString()]) }}">Pay {{ $row['debt']->name }}</button>@endforeach</div>
        <div class="overflow-x-auto rounded-sm border border-base-300 bg-base-100"><table class="table table-sm"><thead><tr><th>Date</th><th>Debt</th><th>Payment</th><th>Interest</th><th>Principal</th><th>Source</th><th>Actions</th></tr></thead><tbody>@forelse($payments as $entry)@php $payment = $entry['payment']; $debt = $entry['debt']; @endphp<tr data-debt-payment-row="{{ $debt->id }}"><td class="whitespace-nowrap">{{ $payment->date->format('d M Y') }}</td><td>{{ $debt->name }}@if($payment->notes)<p class="text-xs opacity-60">{{ $payment->notes }}</p>@endif</td><td class="whitespace-nowrap">{{ $money($payment->amount_cents) }}</td><td class="whitespace-nowrap">{{ $money($payment->interest_cents) }}@if($payment->interest_is_estimated)<span class="block text-xs opacity-60">Estimated</span>@endif</td><td class="whitespace-nowrap">{{ $money($payment->amount_cents - $payment->interest_cents) }}</td><td class="text-xs">{{ $payment->budget_period_name ?: 'Debt record only' }}@if($payment->budget_transaction_id)<span class="badge badge-ghost badge-sm">Budget linked</span>@endif</td><td><div class="flex gap-1"><button class="btn btn-xs" type="button" data-debt-payment-edit="{{ json_encode(['action' => route('debts.payments.store', $debt), 'debt_id' => $debt->id, 'payment_id' => $payment->id, 'amount' => $amount($payment->amount_cents), 'interest' => $amount($payment->interest_cents), 'interest_mode' => $payment->interest_is_estimated ? 'automatic' : 'manual', 'date' => $payment->date->toDateString(), 'notes' => $payment->notes, 'linked' => $payment->budget_transaction_id !== null]) }}">Edit</button><form method="post" action="{{ route('debts.payments.destroy', [$debt, $payment]) }}" data-confirm="Remove this payment? Its principal reduction will be reversed and any linked budget expense will be removed. You can undo this." data-confirm-title="Remove payment?" data-confirm-label="Remove payment">@csrf @method('DELETE')<button class="btn btn-xs btn-ghost text-error">Remove</button></form></div></td></tr>@empty<tr><td colspan="7" class="p-6 text-center opacity-60">No payments recorded yet.</td></tr>@endforelse</tbody></table></div><p class="hidden text-xs opacity-65" data-debt-filter-empty>No payments match this debt.</p>
    @else
        <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">Find a payoff path</h2><p class="mt-1 text-xs opacity-65">Both plans pay minimums first and roll freed payments into the next debt.</p></div><form method="get" action="{{ route('debts.index') }}" class="flex items-end gap-2"><input type="hidden" name="tab" value="plan"><label><span class="label text-xs">Extra per month (ZAR)</span><input class="input w-40" type="number" name="extra" step="0.01" min="0" max="9999999.99" value="{{ $amount($extra) }}" required></label><button class="btn btn-primary">Compare</button></form></div>
        <div class="grid gap-4 md:grid-cols-2">@foreach($plans as $strategy => $plan)<section class="rounded-sm border border-base-300 bg-base-100 p-4"><h3 class="font-semibold">{{ ucfirst($strategy) }}</h3><p class="mt-1 text-xs opacity-65">{{ $strategy === 'snowball' ? 'Smallest balance first, for earlier milestones.' : 'Highest annual interest first, to prioritize expensive debt.' }}</p><div class="mt-4 grid grid-cols-2 gap-3"><div><p class="text-xs opacity-60">Estimated payoff</p><p class="mt-1 text-lg font-semibold">{{ $total === 0 ? 'No outstanding debt' : ($plan['date'] ?? 'Not within 50 years') }}</p>@if($plan['months'] !== null && $total > 0)<p class="text-xs opacity-60">{{ $plan['months'] }} months</p>@endif</div><div><p class="text-xs opacity-60">Estimated interest{{ $plan['months'] === null ? ' within forecast' : '' }}</p><p class="mt-1 text-lg font-semibold">{{ $money($plan['interest']) }}</p></div></div><p class="mt-3 text-xs opacity-65">Monthly payment budget: {{ $money($plan['budget']) }}</p>@if($plan['months'] === null)<p class="mt-2 text-xs text-warning">These payments do not clear the debt within the forecast. Try a larger extra payment and check the rates.</p>@endif<ol class="mt-4 space-y-2 text-xs">@foreach($plan['order'] as $milestone)<li class="flex justify-between gap-3 border-t border-base-300 pt-2"><span>{{ $loop->iteration }}. {{ $milestone['name'] }}</span><span class="font-medium">Month {{ $milestone['month'] }}</span></li>@endforeach</ol></section>@endforeach</div>
        @if($plans['avalanche']['months'] !== null && $plans['snowball']['months'] !== null && $total > 0)<p class="rounded-sm bg-primary/5 p-3 text-sm">Compared with snowball, avalanche estimates {{ $money(abs($plans['snowball']['interest'] - $plans['avalanche']['interest'])) }} {{ $plans['avalanche']['interest'] <= $plans['snowball']['interest'] ? 'less' : 'more' }} interest.</p>@endif
        <p class="text-xs opacity-65">Illustrative monthly estimates from next month: annual rate divided by 12, interest rounded to cents, fixed minimums and a constant payment budget. Actual lender calculations, fees, new borrowing, variable rates, and payment dates can differ. This forecast does not change recorded balances.</p>
    @endif
    @include('debts.dialogs')
    @php
        $oldDebtRow = $rows->first(fn (array $row): bool => $row['debt']->id === (int) old('debt_id'));
        $reopen = null;
        if ($errors->any() && old('amount') !== null && $oldDebtRow !== null) {
            $reopen = ['kind' => 'payment', 'data' => [...old(), 'action' => route('debts.payments.store', $oldDebtRow['debt']), 'linked' => old('payment_id') ? $oldDebtRow['debt']->payments->firstWhere('id', (int) old('payment_id'))?->budget_transaction_id !== null : false]];
        } elseif ($errors->any() && old('name') !== null) {
            $reopen = ['kind' => 'debt', 'data' => [...old(), 'action' => $oldDebtRow === null ? route('debts.store') : route('debts.update', $oldDebtRow['debt']), 'method' => $oldDebtRow === null ? 'POST' : 'PUT', 'has_history' => $oldDebtRow !== null && $oldDebtRow['debt']->payments()->withTrashed()->exists()]];
        }
    @endphp
    <script type="application/json" data-debt-reopen>{!! json_encode($reopen, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR) !!}</script>
</div>
@endsection
