@extends('layouts.app')
@section('title', 'Savings goals')
@section('content')
@php
    $money = fn (int $cents): string => $currencyPrefix.number_format($cents / 100, 2);
    $amount = fn (int $cents): string => number_format($cents / 100, 2, '.', '');
    $tab = in_array(request('tab'), ['contributions', 'planning'], true) ? request('tab') : 'overview';
@endphp
<div class="mx-auto max-w-7xl space-y-4" data-goals-page>
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold">Savings goals</h1><p class="mt-1 text-sm opacity-65">Turn spare money into something you care about.</p></div><button class="btn btn-primary" type="button" data-goal-new>Add goal <x-lucide-plus class="size-4" /></button></div>
    @if(session('status'))<div class="alert alert-success text-sm" role="status">{{ session('status') }}@if(session('undo_contribution'))<form method="post" action="{{ route('goals.contributions.restore', session('undo_contribution')) }}">@csrf<button class="btn btn-ghost">Undo</button></form>@endif</div>@endif
    @if($errors->any())<div class="alert alert-error text-sm" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <nav class="tabs tabs-border" aria-label="Savings goal sections">@foreach(['overview' => 'Overview', 'contributions' => 'Contributions', 'planning' => 'Planning'] as $name => $label)<a @class(['tab', 'tab-active' => $tab === $name]) href="{{ route('goals.index', ['tab' => $name]) }}" @if($tab === $name) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
    @if($tab === 'overview')
        @php $combinedProgress = $target > 0 ? min(100, (int) floor($saved * 100 / $target)) : 0; @endphp
        <div class="grid items-stretch gap-3 sm:grid-cols-3">
            <section class="flex min-w-0 flex-col rounded-sm border border-green-600/15 bg-green-600/5 p-3" aria-label="Savings accumulated towards goals">
                <div class="flex items-center gap-1.5"><x-lucide-piggy-bank class="size-3.5 shrink-0 text-green-600" aria-hidden="true" /><p class="text-[11px] font-medium opacity-70">Saved towards goals</p></div>
                <p class="mt-1.5 break-words text-base font-semibold tracking-tight tabular-nums text-green-600 sm:text-lg">{{ $money($saved) }}</p>
                @if($target > 0)<div class="mt-auto pt-2"><div class="flex flex-wrap items-baseline justify-between gap-1 text-[11px]"><span class="opacity-60">of {{ $money($target) }} combined targets</span><span class="font-semibold tabular-nums text-green-600">{{ number_format($saved / $target * 100, 1) }}%</span></div><div class="mt-1 h-1 overflow-hidden rounded-full bg-green-600/10" role="progressbar" aria-label="Saved towards combined goal targets" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{{ $combinedProgress }}" aria-valuetext="{{ number_format($saved / $target * 100, 1) }}% of combined targets"><div class="h-full rounded-full bg-green-600" style="width: {{ $combinedProgress }}%"></div></div></div>@else<p class="mt-auto pt-2 text-[11px] opacity-60">Add a goal to start saving.</p>@endif
            </section>
            <section class="flex min-w-0 flex-col rounded-sm border border-primary/15 bg-primary/5 p-3" aria-label="Combined savings goal targets">
                <div class="flex items-center gap-1.5"><x-lucide-target class="size-3.5 shrink-0 text-primary" aria-hidden="true" /><p class="text-[11px] font-medium opacity-70">Combined targets</p></div>
                <p class="mt-1.5 break-words text-base font-semibold tracking-tight tabular-nums text-primary sm:text-lg">{{ $money($target) }}</p>
                <p class="mt-auto pt-2 text-[11px] opacity-60">{{ $rows->count() }} {{ str('goal')->plural($rows->count()) }} &middot; {{ $completed }} {{ str('complete')->plural($completed) }}</p>
            </section>
            <section class="flex min-w-0 flex-col rounded-sm border border-orange-600/15 bg-orange-600/5 p-3" aria-label="Monthly savings plan">
                <div class="flex items-center gap-1.5"><x-lucide-calendar-days class="size-3.5 shrink-0 text-orange-600" aria-hidden="true" /><p class="text-[11px] font-medium opacity-70">Monthly saving plan</p></div>
                <p class="mt-1.5 break-words text-base font-semibold tracking-tight tabular-nums text-orange-600 sm:text-lg">{{ $money($monthly) }}</p>
                <p class="mt-auto pt-2 text-[11px] opacity-60">Planned across active goals</p>
            </section>
        </div>
        @include('goals.forecast')
        <div class="grid items-stretch gap-3 md:grid-cols-2">
            @forelse($rows as $row)
                @php
                    $goal = $row['goal'];
                    $link = $categories->first(fn (array $category): bool => $category['budget_id'] === $goal->budget_id && $category['name'] === $goal->category_name);
                    $edit = ['original_asset_id' => $goal->asset_id, 'asset_id' => $goal->asset_id, 'goal_id' => $goal->id, 'action' => route('goals.update', $goal), 'name' => $goal->name, 'kind' => $goal->kind, 'target' => $amount($goal->target_cents), 'opening' => $amount($goal->opening_cents), 'start_date' => $goal->start_date->toDateString(), 'target_date' => $goal->target_date?->toDateString(), 'monthly' => $amount($goal->monthly_cents), 'category_id' => $link['id'] ?? '', 'notes' => $goal->notes, 'has_history' => $goal->contributions()->withTrashed()->exists()];
                    $contribute = ['goal_id' => $goal->id, 'action' => route('goals.contributions.store', $goal), 'amount' => $row['monthRemaining'] > 0 ? $amount($row['monthRemaining']) : '', 'date' => today()->toDateString(), 'budget_id' => $goal->budget_id, 'asset_id' => $goal->asset_id, 'account_name' => $goal->account?->name, 'category_name' => $goal->category_name];
                @endphp
                <article class="flex flex-col gap-3 rounded-sm border border-base-300 bg-base-100 p-4 last:odd:md:col-span-2">
                    <div class="flex items-start justify-between gap-2"><div><h2 class="font-semibold">{{ $goal->name }}</h2><span @class(['badge badge-sm mt-1 rounded-sm', 'badge-success' => in_array($row['status'], ['Complete', 'On track']), 'badge-warning' => in_array($row['status'], ['Needs a boost', 'Past target date']), 'badge-ghost' => $row['status'] === 'Building savings'])>{{ $row['status'] }}</span></div><button class="btn btn-ghost" type="button" data-goal-edit="{{ json_encode($edit) }}">Edit</button></div>
                    <div class="flex flex-wrap items-baseline justify-between gap-2"><p class="text-2xl font-bold">{{ $money($row['saved']) }}</p><p class="text-xs opacity-60">of {{ $money($goal->target_cents) }} &middot; {{ $row['progress'] }}%</p></div>
                    <progress class="progress progress-primary h-2 w-full rounded-sm" value="{{ $row['progress'] }}" max="100" aria-label="{{ $goal->name }} savings progress"></progress>
                    <div class="grid gap-2 text-xs sm:grid-cols-3"><div><p class="opacity-60">Still to save</p><p class="mt-1 font-medium">{{ $money($row['remaining']) }}</p></div><div><p class="opacity-60">Monthly plan</p><p class="mt-1 font-medium">{{ $row['monthly'] > 0 ? $money($row['monthly']) : 'Set an amount or date' }}</p></div><div><p class="opacity-60">Target date</p><p class="mt-1 font-medium">{{ $goal->target_date?->format('d M Y') ?? 'At your own pace' }}</p></div></div>
                    @if($row['remaining'] === 0)<p class="text-sm text-success">Goal reached. Your contributions have paid off.</p>@elseif($goal->target_date?->lt(today()))<p class="text-xs text-warning">{{ $money($row['remaining']) }} remains. Set a new target date or increase your next contribution.</p>@elseif($row['needed'] !== null)<p class="rounded-sm bg-primary/5 p-2 text-xs">Save {{ $money($row['needed']) }} per month from now through {{ $goal->target_date->format('M Y') }} to reach this target.</p>@endif
                    @if($row['monthRemaining'] > 0)<p class="text-xs opacity-65">{{ $money($row['monthRemaining']) }} left in this month's saving plan.</p>@elseif($row['monthly'] > 0 && $row['remaining'] > 0)<p class="text-xs text-success">This month's saving plan is covered.</p>@endif
                    @if($goal->asset_id)<p class="text-xs opacity-60">Account: {{ $goal->account?->name ?? 'Removed account / restore or choose another' }} &middot; Saved money is protected automatically.</p>@else<p class="text-xs text-warning">Link an account to include these savings in liquidity.</p>@endif
                    @if($goal->budget)<p class="text-xs opacity-60">Budget link: {{ $goal->budget->name }} / {{ $goal->category_name }}</p>@endif
                    @if($goal->notes)<p class="text-xs opacity-65">{{ $goal->notes }}</p>@endif
                    <div class="mt-auto flex flex-wrap items-center justify-between gap-2"><button class="btn btn-primary" type="button" data-goal-contribute="{{ json_encode($contribute) }}">Add contribution</button><form method="post" action="{{ route('goals.destroy', $goal) }}" data-confirm="Delete this goal and its contribution history? Recorded budget expenses will be kept." data-confirm-title="Delete savings goal?" data-confirm-label="Delete goal">@csrf @method('DELETE')<button class="btn btn-ghost text-error">Delete</button></form></div>
                </article>
            @empty
                <div class="rounded-sm border border-dashed border-base-300 p-8 text-center md:col-span-2"><x-lucide-target class="mx-auto size-8 text-primary" /><h2 class="mt-3 font-semibold">Give your savings a purpose</h2><p class="mt-1 text-sm opacity-65">Start with an emergency fund, a holiday, a deposit, or your own goal.</p><div class="mt-4 flex flex-wrap justify-center gap-2">@foreach(['emergency' => 'Emergency fund', 'holiday' => 'Holiday', 'deposit' => 'Deposit'] as $kind => $name)<button class="btn btn-outline" type="button" data-goal-new="{{ json_encode(['name' => $name, 'kind' => $kind]) }}">{{ $name }}</button>@endforeach</div><a class="link mt-3 inline-block text-xs" href="{{ route('goals.index', ['tab' => 'planning']) }}">Help me choose an emergency-fund target</a></div>
            @endforelse
        </div>
        <section class="rounded-sm border border-base-300 bg-base-100 p-4" aria-labelledby="savings-trend-title"><div class="flex items-center justify-between gap-2"><h2 id="savings-trend-title" class="font-semibold">Contributions over time</h2><span class="text-xs opacity-60">Last six months</span></div>@php $peak = max(1, $trends->max('amount')); @endphp<div class="mt-3 grid grid-cols-6 gap-2">@foreach($trends as $month)<div class="text-center"><p class="truncate text-xs opacity-65" title="{{ $money($month['amount']) }}">{{ $money($month['amount']) }}</p><div class="mt-2 flex h-20 items-end justify-center"><div class="w-full max-w-12 rounded-sm bg-primary/70" style="height: {{ (int) round($month['amount'] / $peak * 100) }}%" role="img" aria-label="{{ $month['date'] }}: {{ $money($month['amount']) }}"></div></div><p class="mt-2 text-xs opacity-60">{{ $month['label'] }}</p></div>@endforeach</div><p class="mt-2 text-xs opacity-60">Recorded contributions only. Starting savings are excluded.</p></section>
        <p class="text-xs opacity-60">Progress tracks the amounts you record, without investment returns. On-track status compares saved money with a straight-line path from your starting date to your target date.</p>
    @elseif($tab === 'contributions')
        <div class="flex flex-wrap items-end justify-between gap-2"><div><h2 class="font-semibold">Contribution history</h2><p class="text-xs opacity-65">Newest first. Budget-linked contributions count once in both places.</p></div><label><span class="label text-xs">Goal</span><select class="select max-w-64" data-goal-filter><option value="">All goals</option>@foreach($rows as $row)<option value="{{ $row['goal']->id }}" @selected((string) request('goal') === (string) $row['goal']->id)>{{ $row['goal']->name }}</option>@endforeach</select></label></div>
        <div class="flex flex-wrap gap-2">@foreach($rows as $row)<button class="btn btn-outline" type="button" data-goal-contribute="{{ json_encode(['goal_id' => $row['goal']->id, 'action' => route('goals.contributions.store', $row['goal']), 'date' => today()->toDateString(), 'budget_id' => $row['goal']->budget_id, 'asset_id' => $row['goal']->asset_id, 'account_name' => $row['goal']->account?->name, 'category_name' => $row['goal']->category_name]) }}">Add to {{ $row['goal']->name }}</button>@endforeach</div>
        <div class="overflow-x-auto rounded-sm border border-base-300 bg-base-100"><table class="table table-sm"><thead><tr><th>Date</th><th>Goal</th><th>Amount</th><th>Source</th><th>Actions</th></tr></thead><tbody>@forelse($contributions as $record)@php $entry = $record['entry']; $goal = $record['goal']; @endphp<tr data-goal-row="{{ $goal->id }}"><td class="whitespace-nowrap">{{ $entry->date->format('d M Y') }}</td><td>{{ $goal->name }}@if($entry->notes)<p class="text-xs opacity-60">{{ $entry->notes }}</p>@endif</td><td class="whitespace-nowrap">{{ $money($entry->amount_cents) }}</td><td class="text-xs">{{ $entry->budget_period_name ?: 'Goal record only' }}@if($entry->asset_id)<p class="mt-1 opacity-60">{{ $entry->money_origin === 'new' ? 'New money / balance updated' : 'Existing money / balance unchanged' }}</p>@endif @if($entry->budget_transaction_id)<span class="badge badge-ghost badge-sm rounded-sm">Budget linked</span>@endif</td><td><div class="flex gap-1"><button class="btn btn-xs" type="button" data-contribution-edit="{{ json_encode(['goal_id' => $goal->id, 'action' => route('goals.contributions.store', $goal), 'contribution_id' => $entry->id, 'money_origin' => $entry->money_origin, 'contribution_asset_id' => $entry->asset_id, 'contribution_account_name' => $entry->account?->name ?? ($entry->asset_id ? 'Removed account' : null), 'amount' => $amount($entry->amount_cents), 'date' => $entry->date->toDateString(), 'notes' => $entry->notes, 'budget_id' => $goal->budget_id, 'asset_id' => $goal->asset_id, 'account_name' => $goal->account?->name, 'category_name' => $goal->category_name, 'linked' => $entry->budget_transaction_id !== null]) }}">Edit</button><form method="post" action="{{ route('goals.contributions.destroy', [$goal, $entry]) }}" data-confirm="Remove this contribution? Savings progress and its automatic reserve will decrease. Any linked budget expense will be removed, and new-money account entries will be reversed. You can undo this." data-confirm-title="Remove contribution?" data-confirm-label="Remove">@csrf @method('DELETE')<button class="btn btn-xs btn-ghost text-error">Remove</button></form></div></td></tr>@empty<tr><td colspan="5" class="p-6 text-center opacity-60">No contributions recorded yet.</td></tr>@endforelse</tbody></table></div><p class="hidden text-xs opacity-65" data-goal-filter-empty>No contributions match this goal.</p>
    @else
        @include('goals.planning')
    @endif
    @include('goals.dialogs')
    @php
        $oldRow = $rows->first(fn (array $row): bool => $row['goal']->id === (int) old('goal_id'));
        $reopen = null;
        if ($errors->any() && old('amount') !== null && $oldRow !== null) {
            $entry = $oldRow['goal']->contributions->firstWhere('id', (int) old('contribution_id'));
            $reopen = ['kind' => 'contribution', 'data' => [...old(), 'action' => route('goals.contributions.store', $oldRow['goal']), 'budget_id' => $oldRow['goal']->budget_id, 'asset_id' => $oldRow['goal']->asset_id, 'account_name' => $oldRow['goal']->account?->name, 'contribution_asset_id' => $entry?->asset_id, 'contribution_account_name' => $entry?->account?->name ?? ($entry?->asset_id ? 'Removed account' : null), 'category_name' => $oldRow['goal']->category_name, 'linked' => $entry?->budget_transaction_id !== null]];
        } elseif ($errors->any() && old('name') !== null) {
            $reopen = ['kind' => 'goal', 'data' => [...old(), 'action' => $oldRow ? route('goals.update', $oldRow['goal']) : route('goals.store'), 'method' => $oldRow ? 'PUT' : 'POST', 'original_asset_id' => $oldRow ? $oldRow['goal']->asset_id : null, 'has_history' => $oldRow ? $oldRow['goal']->contributions()->withTrashed()->exists() : false]];
        }
    @endphp
    <script type="application/json" data-goal-reopen>{!! json_encode($reopen, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR) !!}</script>
</div>
@endsection
